"""add social statistics history

Revision ID: e5d69d6a6de3
Revises: 9b3d6f4a2c11
Create Date: 2026-07-24 21:06:38.044684
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5d69d6a6de3'
down_revision: Union[str, Sequence[str], None] = '9b3d6f4a2c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_stat_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_stat_snapshots_id'), 'social_stat_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_social_stat_snapshots_platform'), 'social_stat_snapshots', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_stat_snapshots_platform'), table_name='social_stat_snapshots')
    op.drop_index(op.f('ix_social_stat_snapshots_id'), table_name='social_stat_snapshots')
    op.drop_table('social_stat_snapshots')
    # ### end Alembic commands ###
